(function(exports, require, module, __filename, __dirname) {// Claude Code is a Beta product per Anthropic's Commercial Terms of Service.
// By using Claude Code, you agree that all code acceptance or rejection decisions you make,
// and the associated conversations in context, constitute Feedback under Anthropic's Commercial Terms,
// and may be used to improve Anthropic's products, including training models.
// You are responsible for reviewing any code suggestions before use.

// (c) Anthropic PBC. All rights reserved. Use is subject to the Legal Agreements outlined here: https://code.claude.com/docs/en/legal-and-compliance.

// Version: 2.1.87
var o=Object.create;var{getPrototypeOf:c,defineProperty:A,getOwnPropertyNames:t,getOwnPropertyDescriptor:B}=Object,q=Object.prototype.hasOwnProperty;function D(T){return this[T]}var y=(T,R,_)=>{var h=t(R);for(let i of h)if(!q.call(T,i)&&i!=="default")A(T,i,{get:D.bind(R,i),enumerable:!0});if(_){for(let i of h)if(!q.call(_,i)&&i!=="default")A(_,i,{get:D.bind(R,i),enumerable:!0});return _}},H,n,J=(T,R,_)=>{var h=T!=null&&typeof T==="object";if(h){var i=R?H??=new WeakMap:n??=new WeakMap,a=i.get(T);if(a)return a}_=T!=null?o(c(T)):{};let r=R||!T||!T.__esModule?A(_,"default",{value:T,enumerable:!0}):_;for(let e of t(T))if(!q.call(r,e))A(r,e,{get:D.bind(T,e),enumerable:!0});if(h)i.set(T,r);return r},L=(T)=>{var R=(C??=new WeakMap).get(T),_;if(R)return R;if(R=A({},"__esModule",{value:!0}),T&&typeof T==="object"||typeof T==="function"){for(var h of t(T))if(!q.call(R,h))A(R,h,{get:D.bind(T,h),enumerable:!(_=B(T,h))||_.enumerable})}return C.set(T,R),R},C,O=(T,R)=>()=>(R||T((R={exports:{}}).exports,R),R.exports);var s=(T)=>T;function l(T,R){this[T]=s.bind(null,R)}var b=(T,R)=>{for(var _ in R)A(T,_,{get:R[_],enumerable:!0,configurable:!0,set:l.bind(R,_)})};var W=(T,R)=>()=>(T&&(R=T(T=0)),R);var g=(T,R,_)=>{if(R!=null){if(typeof R!=="object"&&typeof R!=="function")throw TypeError('Object expected to be assigned to "using" declaration');let h;if(_)h=R[Symbol.asyncDispose];if(h===void 0)h=R[Symbol.dispose];if(typeof h!=="function")throw TypeError("Object not disposable");T.push([_,h,R])}else if(_)T.push([_]);return R},P=(T,R,_)=>{let h=(a)=>R=_?new SuppressedError(a,R,"An error was suppressed during disposal"):(_=!0,a),i=(a)=>{while(a=T.pop())try{var r=a[1]&&a[1].call(a[2]);if(a[0])return Promise.resolve(r).then(i,(e)=>(h(e),i()))}catch(e){h(e)}if(_)throw R};return i()};var k=O((p,d)=>{d.exports=require("/$bunfs/root/audio-capture.node")});module.exports=k();})