  var g37 = d((GHO, B37) => {
    /*!
  Copyright 2013 Lovell Fuller and others.
  SPDX-License-Identifier: Apache-2.0
*/ var Mo4 = require("util"),
      hI6 = require("stream"),
      Jo4 = Pd();
    CiH();
    var Po4 = Mo4.debuglog("sharp"),
      Xo4 = (H) => {
        vTH.queue.emit("change", H);
      },
      vTH = function (H, _) {
        if (arguments.length === 1 && !Jo4.defined(H)) throw Error("Invalid input");
        if (!(this instanceof vTH)) return new vTH(H, _);
        return (
          hI6.Duplex.call(this),
          (this.options = {
            topOffsetPre: -1,
            leftOffsetPre: -1,
            widthPre: -1,
            heightPre: -1,
            topOffsetPost: -1,
            leftOffsetPost: -1,
            widthPost: -1,
            heightPost: -1,
            width: -1,
            height: -1,
            canvas: "crop",
            position: 0,
            resizeBackground: [0, 0, 0, 255],
            angle: 0,
            rotationAngle: 0,
            rotationBackground: [0, 0, 0, 255],
            rotateBefore: !1,
            orientBefore: !1,
            flip: !1,
            flop: !1,
            extendTop: 0,
            extendBottom: 0,
            extendLeft: 0,
            extendRight: 0,
            extendBackground: [0, 0, 0, 255],
            extendWith: "background",
            withoutEnlargement: !1,
            withoutReduction: !1,
            affineMatrix: [],
            affineBackground: [0, 0, 0, 255],
            affineIdx: 0,
            affineIdy: 0,
            affineOdx: 0,
            affineOdy: 0,
            affineInterpolator: this.constructor.interpolators.bilinear,
            kernel: "lanczos3",
            fastShrinkOnLoad: !0,
            tint: [-1, 0, 0, 0],
            flatten: !1,
            flattenBackground: [0, 0, 0],
            unflatten: !1,
            negate: !1,
            negateAlpha: !0,
            medianSize: 0,
            blurSigma: 0,
            precision: "integer",
            minAmpl: 0.2,
            sharpenSigma: 0,
            sharpenM1: 1,
            sharpenM2: 2,
            sharpenX1: 2,
            sharpenY2: 10,
            sharpenY3: 20,
            threshold: 0,
            thresholdGrayscale: !0,
            trimBackground: [],
            trimThreshold: -1,
            trimLineArt: !1,
            dilateWidth: 0,
            erodeWidth: 0,
            gamma: 0,
            gammaOut: 0,
            greyscale: !1,
            normalise: !1,
            normaliseLower: 1,
            normaliseUpper: 99,
            claheWidth: 0,
            claheHeight: 0,
            claheMaxSlope: 3,
            brightness: 1,
            saturation: 1,
            hue: 0,
            lightness: 0,
            booleanBufferIn: null,
            booleanFileIn: "",
            joinChannelIn: [],
            extractChannel: -1,
            removeAlpha: !1,
            ensureAlpha: -1,
            colourspace: "srgb",
            colourspacePipeline: "last",
            composite: [],
            fileOut: "",
            formatOut: "input",
            streamOut: !1,
            keepMetadata: 0,
            withMetadataOrientation: -1,
            withMetadataDensity: 0,
            withIccProfile: "",
            withExif: {},
            withExifMerge: !0,
            withXmp: "",
            resolveWithObject: !1,
            loop: -1,
            delay: [],
            jpegQuality: 80,
            jpegProgressive: !1,
            jpegChromaSubsampling: "4:2:0",
            jpegTrellisQuantisation: !1,
            jpegOvershootDeringing: !1,
            jpegOptimiseScans: !1,
            jpegOptimiseCoding: !0,
            jpegQuantisationTable: 0,
            pngProgressive: !1,
            pngCompressionLevel: 6,
            pngAdaptiveFiltering: !1,
            pngPalette: !1,
            pngQuality: 100,
            pngEffort: 7,
            pngBitdepth: 8,
            pngDither: 1,
            jp2Quality: 80,
            jp2TileHeight: 512,
            jp2TileWidth: 512,
            jp2Lossless: !1,
            jp2ChromaSubsampling: "4:4:4",
            webpQuality: 80,
            webpAlphaQuality: 100,
            webpLossless: !1,
            webpNearLossless: !1,
            webpSmartSubsample: !1,
            webpSmartDeblock: !1,
            webpPreset: "default",
            webpEffort: 4,
            webpMinSize: !1,
            webpMixed: !1,
            gifBitdepth: 8,
            gifEffort: 7,
            gifDither: 1,
            gifInterFrameMaxError: 0,
            gifInterPaletteMaxError: 3,
            gifKeepDuplicateFrames: !1,
            gifReuse: !0,
            gifProgressive: !1,
            tiffQuality: 80,
            tiffCompression: "jpeg",
            tiffBigtiff: !1,
            tiffPredictor: "horizontal",
            tiffPyramid: !1,
            tiffMiniswhite: !1,
            tiffBitdepth: 8,
            tiffTile: !1,
            tiffTileHeight: 256,
            tiffTileWidth: 256,
            tiffXres: 1,
            tiffYres: 1,
            tiffResolutionUnit: "inch",
            heifQuality: 50,
            heifLossless: !1,
            heifCompression: "av1",
            heifEffort: 4,
            heifChromaSubsampling: "4:4:4",
            heifBitdepth: 8,
            jxlDistance: 1,
            jxlDecodingTier: 0,
            jxlEffort: 7,
            jxlLossless: !1,
            rawDepth: "uchar",
            tileSize: 256,
            tileOverlap: 0,
            tileContainer: "fs",
            tileLayout: "dz",
            tileFormat: "last",
            tileDepth: "last",
            tileAngle: 0,
            tileSkipBlanks: -1,
            tileBackground: [255, 255, 255, 255],
            tileCentre: !1,
            tileId: "https://example.com/iiif",
            tileBasename: "",
            timeoutSeconds: 0,
            linearA: [],
            linearB: [],
            pdfBackground: [255, 255, 255, 255],
            debuglog: (q) => {
              this.emit("warning", q), Po4(q);
            },
            queueListener: Xo4,
          }),
          (this.options.input = this._createInputDescriptor(H, _, { allowStream: !0 })),
          this
        );
      };
    Object.setPrototypeOf(vTH.prototype, hI6.Duplex.prototype);
    Object.setPrototypeOf(vTH, hI6.Duplex);
    function Wo4() {
      let H = this.constructor.call(),
        { debuglog: _, queueListener: q, ...$ } = this.options;
      if (
        ((H.options = structuredClone($)),
        (H.options.debuglog = _),
        (H.options.queueListener = q),
        this._isStreamInput())
      )
        this.on("finish", () => {
          this._flattenBufferIn(), (H.options.input.buffer = this.options.input.buffer), H.emit("finish");
        });
      return H;
    }
    Object.assign(vTH.prototype, { clone: Wo4 });
    B37.exports = vTH;
  });
