  var mz7 = d((_6O, xz7) => {
    var Ie4 = [
        "as",
        "in",
        "of",
        "if",
        "for",
        "while",
        "finally",
        "var",
        "new",
        "function",
        "do",
        "return",
        "void",
        "else",
        "break",
        "catch",
        "instanceof",
        "with",
        "throw",
        "case",
        "default",
        "try",
        "switch",
        "continue",
        "typeof",
        "delete",
        "let",
        "yield",
        "const",
        "class",
        "debugger",
        "async",
        "await",
        "static",
        "import",
        "from",
        "export",
        "extends",
      ],
      ue4 = ["true", "false", "null", "undefined", "NaN", "Infinity"],
      xe4 = [
        "Intl",
        "DataView",
        "Number",
        "Math",
        "Date",
        "String",
        "RegExp",
        "Object",
        "Function",
        "Boolean",
        "Error",
        "Symbol",
        "Set",
        "Map",
        "WeakSet",
        "WeakMap",
        "Proxy",
        "Reflect",
        "JSON",
        "Promise",
        "Float64Array",
        "Int16Array",
        "Int32Array",
        "Int8Array",
        "Uint16Array",
        "Uint32Array",
        "Float32Array",
        "Array",
        "Uint8Array",
        "Uint8ClampedArray",
        "ArrayBuffer",
        "BigInt64Array",
        "BigUint64Array",
        "BigInt",
      ],
      me4 = ["EvalError", "InternalError", "RangeError", "ReferenceError", "SyntaxError", "TypeError", "URIError"],
      pe4 = [
        "setInterval",
        "setTimeout",
        "clearInterval",
        "clearTimeout",
        "require",
        "exports",
        "eval",
        "isFinite",
        "isNaN",
        "parseFloat",
        "parseInt",
        "decodeURI",
        "decodeURIComponent",
        "encodeURI",
        "encodeURIComponent",
        "escape",
        "unescape",
      ],
      Be4 = ["arguments", "this", "super", "console", "window", "document", "localStorage", "module", "global"],
      ge4 = [].concat(pe4, Be4, xe4, me4);
    function de4(H) {
      let _ = ["npm", "print"],
        q = ["yes", "no", "on", "off"],
        $ = ["then", "unless", "until", "loop", "by", "when", "and", "or", "is", "isnt", "not"],
        K = ["var", "const", "let", "function", "static"],
        O = (j) => (M) => !j.includes(M),
        T = { keyword: Ie4.concat($).filter(O(K)), literal: ue4.concat(q), built_in: ge4.concat(_) },
        z = "[A-Za-z$_][0-9A-Za-z$_]*",
        A = { className: "subst", begin: /#\{/, end: /\}/, keywords: T },
        f = [
          H.BINARY_NUMBER_MODE,
          H.inherit(H.C_NUMBER_MODE, { starts: { end: "(\\s*/)?", relevance: 0 } }),
          {
            className: "string",
            variants: [
              { begin: /'''/, end: /'''/, contains: [H.BACKSLASH_ESCAPE] },
              { begin: /'/, end: /'/, contains: [H.BACKSLASH_ESCAPE] },
              { begin: /"""/, end: /"""/, contains: [H.BACKSLASH_ESCAPE, A] },
              { begin: /"/, end: /"/, contains: [H.BACKSLASH_ESCAPE, A] },
            ],
          },
          {
            className: "regexp",
            variants: [
              { begin: "///", end: "///", contains: [A, H.HASH_COMMENT_MODE] },
              { begin: "//[gim]{0,3}(?=\\W)", relevance: 0 },
              { begin: /\/(?![ *]).*?(?![\\]).\/[gim]{0,3}(?=\W)/ },
            ],
          },
          { begin: "@[A-Za-z$_][0-9A-Za-z$_]*" },
          {
            subLanguage: "javascript",
            excludeBegin: !0,
            excludeEnd: !0,
            variants: [
              { begin: "```", end: "```" },
              { begin: "`", end: "`" },
            ],
          },
        ];
      A.contains = f;
      let w = H.inherit(H.TITLE_MODE, { begin: "[A-Za-z$_][0-9A-Za-z$_]*" }),
        Y = "(\\(.*\\)\\s*)?\\B[-=]>",
        D = {
          className: "params",
          begin: "\\([^\\(]",
          returnBegin: !0,
          contains: [{ begin: /\(/, end: /\)/, keywords: T, contains: ["self"].concat(f) }],
        };
      return {
        name: "CoffeeScript",
        aliases: ["coffee", "cson", "iced"],
        keywords: T,
        illegal: /\/\*/,
        contains: f.concat([
          H.COMMENT("###", "###"),
          H.HASH_COMMENT_MODE,
          {
            className: "function",
            begin: "^\\s*[A-Za-z$_][0-9A-Za-z$_]*\\s*=\\s*" + Y,
            end: "[-=]>",
            returnBegin: !0,
            contains: [w, D],
          },
          {
            begin: /[:\(,=]\s*/,
            relevance: 0,
            contains: [{ className: "function", begin: Y, end: "[-=]>", returnBegin: !0, contains: [D] }],
          },
          {
            className: "class",
            beginKeywords: "class",
            end: "$",
            illegal: /[:="\[\]]/,
            contains: [{ beginKeywords: "extends", endsWithParent: !0, illegal: /[:="\[\]]/, contains: [w] }, w],
          },
          { begin: "[A-Za-z$_][0-9A-Za-z$_]*:", end: ":", returnBegin: !0, returnEnd: !0, relevance: 0 },
        ]),
      };
    }
    xz7.exports = de4;
  });
