  var Rw7 = d((P8O, Gw7) => {
    var e_1 = [
        "as",
        "in",
        "of",
        "if",
        "for",
        "while",
        "finally",
        "var",
        "new",
        "function",
        "do",
        "return",
        "void",
        "else",
        "break",
        "catch",
        "instanceof",
        "with",
        "throw",
        "case",
        "default",
        "try",
        "switch",
        "continue",
        "typeof",
        "delete",
        "let",
        "yield",
        "const",
        "class",
        "debugger",
        "async",
        "await",
        "static",
        "import",
        "from",
        "export",
        "extends",
      ],
      H61 = ["true", "false", "null", "undefined", "NaN", "Infinity"],
      _61 = [
        "Intl",
        "DataView",
        "Number",
        "Math",
        "Date",
        "String",
        "RegExp",
        "Object",
        "Function",
        "Boolean",
        "Error",
        "Symbol",
        "Set",
        "Map",
        "WeakSet",
        "WeakMap",
        "Proxy",
        "Reflect",
        "JSON",
        "Promise",
        "Float64Array",
        "Int16Array",
        "Int32Array",
        "Int8Array",
        "Uint16Array",
        "Uint32Array",
        "Float32Array",
        "Array",
        "Uint8Array",
        "Uint8ClampedArray",
        "ArrayBuffer",
        "BigInt64Array",
        "BigUint64Array",
        "BigInt",
      ],
      q61 = ["EvalError", "InternalError", "RangeError", "ReferenceError", "SyntaxError", "TypeError", "URIError"],
      $61 = [
        "setInterval",
        "setTimeout",
        "clearInterval",
        "clearTimeout",
        "require",
        "exports",
        "eval",
        "isFinite",
        "isNaN",
        "parseFloat",
        "parseInt",
        "decodeURI",
        "decodeURIComponent",
        "encodeURI",
        "encodeURIComponent",
        "escape",
        "unescape",
      ],
      K61 = ["arguments", "this", "super", "console", "window", "document", "localStorage", "module", "global"],
      O61 = [].concat($61, K61, _61, q61);
    function T61(H) {
      let _ = ["npm", "print"],
        q = ["yes", "no", "on", "off", "it", "that", "void"],
        $ = [
          "then",
          "unless",
          "until",
          "loop",
          "of",
          "by",
          "when",
          "and",
          "or",
          "is",
          "isnt",
          "not",
          "it",
          "that",
          "otherwise",
          "from",
          "to",
          "til",
          "fallthrough",
          "case",
          "enum",
          "native",
          "list",
          "map",
          "__hasProp",
          "__extends",
          "__slice",
          "__bind",
          "__indexOf",
        ],
        K = { keyword: e_1.concat($), literal: H61.concat(q), built_in: O61.concat(_) },
        O = "[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*",
        T = H.inherit(H.TITLE_MODE, { begin: "[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*" }),
        z = { className: "subst", begin: /#\{/, end: /\}/, keywords: K },
        A = { className: "subst", begin: /#[A-Za-z$_]/, end: /(?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*/, keywords: K },
        f = [
          H.BINARY_NUMBER_MODE,
          {
            className: "number",
            begin:
              "(\\b0[xX][a-fA-F0-9_]+)|(\\b\\d(\\d|_\\d)*(\\.(\\d(\\d|_\\d)*)?)?(_*[eE]([-+]\\d(_\\d|\\d)*)?)?[_a-z]*)",
            relevance: 0,
            starts: { end: "(\\s*/)?", relevance: 0 },
          },
          {
            className: "string",
            variants: [
              { begin: /'''/, end: /'''/, contains: [H.BACKSLASH_ESCAPE] },
              { begin: /'/, end: /'/, contains: [H.BACKSLASH_ESCAPE] },
              { begin: /"""/, end: /"""/, contains: [H.BACKSLASH_ESCAPE, z, A] },
              { begin: /"/, end: /"/, contains: [H.BACKSLASH_ESCAPE, z, A] },
              { begin: /\\/, end: /(\s|$)/, excludeEnd: !0 },
            ],
          },
          {
            className: "regexp",
            variants: [
              { begin: "//", end: "//[gim]*", contains: [z, H.HASH_COMMENT_MODE] },
              { begin: /\/(?![ *])(\\.|[^\\\n])*?\/[gim]*(?=\W)/ },
            ],
          },
          { begin: "@[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*" },
          { begin: "``", end: "``", excludeBegin: !0, excludeEnd: !0, subLanguage: "javascript" },
        ];
      z.contains = f;
      let w = {
          className: "params",
          begin: "\\(",
          returnBegin: !0,
          contains: [{ begin: /\(/, end: /\)/, keywords: K, contains: ["self"].concat(f) }],
        },
        Y = { begin: "(#=>|=>|\\|>>|-?->|!->)" };
      return {
        name: "LiveScript",
        aliases: ["ls"],
        keywords: K,
        illegal: /\/\*/,
        contains: f.concat([
          H.COMMENT("\\/\\*", "\\*\\/"),
          H.HASH_COMMENT_MODE,
          Y,
          {
            className: "function",
            contains: [T, w],
            returnBegin: !0,
            variants: [
              {
                begin: "([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\\s*(?:=|:=)\\s*)?(\\(.*\\)\\s*)?\\B->\\*?",
                end: "->\\*?",
              },
              {
                begin:
                  "([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\\s*(?:=|:=)\\s*)?!?(\\(.*\\)\\s*)?\\B[-~]{1,2}>\\*?",
                end: "[-~]{1,2}>\\*?",
              },
              {
                begin:
                  "([A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*\\s*(?:=|:=)\\s*)?(\\(.*\\)\\s*)?\\B!?[-~]{1,2}>\\*?",
                end: "!?[-~]{1,2}>\\*?",
              },
            ],
          },
          {
            className: "class",
            beginKeywords: "class",
            end: "$",
            illegal: /[:="\[\]]/,
            contains: [{ beginKeywords: "extends", endsWithParent: !0, illegal: /[:="\[\]]/, contains: [T] }, T],
          },
          {
            begin: "[A-Za-z$_](?:-[0-9A-Za-z$_]|[0-9A-Za-z$_])*:",
            end: ":",
            returnBegin: !0,
            returnEnd: !0,
            relevance: 0,
          },
        ]),
      };
    }
    Gw7.exports = T61;
  });
