use super::*;

/// At startup, the TUI should display the project directory as the first
/// display block (a SystemMessage), followed by a `pwd` BashOutput.
/// This gives the user immediate visual feedback about which directory
/// Chlodwig is running in.

#[test]
fn test_startup_shows_project_dir_system_message() {
    // The startup display blocks are generated by `App::startup_project_dir_blocks()`.
    let app = App::new("m".into());
    let blocks = app.startup_project_dir_blocks();

    // First block: SystemMessage with the project directory path
    assert!(blocks.len() >= 1, "Should have at least one startup block");
    match &blocks[0] {
        DisplayBlock::SystemMessage(msg) => {
            // Should contain the App's cwd
            let cwd = app.cwd.display().to_string();
            assert!(
                msg.contains(&cwd),
                "SystemMessage should contain CWD '{cwd}', got: {msg}"
            );
        }
        other => panic!("First startup block should be SystemMessage, got: {other:?}"),
    }
}

#[test]
fn test_startup_shows_pwd_bash_output() {
    let app = App::new("m".into());
    let blocks = app.startup_project_dir_blocks();

    // Second block: BashOutput with `pwd` command
    assert!(blocks.len() >= 2, "Should have at least two startup blocks, got {}", blocks.len());
    match &blocks[1] {
        DisplayBlock::BashOutput { command, raw_output } => {
            assert_eq!(command, "pwd", "Command should be 'pwd', got: {command}");
            // The output should be a non-empty path
            let trimmed = raw_output.trim();
            assert!(!trimmed.is_empty(), "pwd output should not be empty");
            // It should be a valid path (starts with /)
            assert!(
                trimmed.starts_with('/') || trimmed.contains(':'),
                "pwd output should be an absolute path, got: {trimmed}"
            );
        }
        other => panic!("Second startup block should be BashOutput, got: {other:?}"),
    }
}

#[test]
fn test_startup_blocks_render_without_panic() {
    let mut app = App::new("test-model".into());
    let blocks = app.startup_project_dir_blocks();
    for block in blocks {
        app.display_blocks.push(block);
    }
    app.mark_dirty();
    app.rebuild_lines();

    // Should have rendered lines (at least the system message + pwd output)
    assert!(
        !app.rendered_lines.is_empty(),
        "Startup blocks should produce rendered lines"
    );
}

#[test]
fn test_startup_project_dir_contains_directory_label() {
    let app = App::new("m".into());
    let blocks = app.startup_project_dir_blocks();
    match &blocks[0] {
        DisplayBlock::SystemMessage(msg) => {
            // Should have some label like "Project" or "Working directory"
            assert!(
                msg.contains("cwd"),
                "SystemMessage should contain 'cwd' label, got: {msg}"
            );
        }
        _ => panic!("Expected SystemMessage"),
    }
}

#[test]
fn test_event_loop_calls_startup_project_dir_blocks() {
    // Verify the event_loop source code calls startup_project_dir_blocks()
    // so the blocks are actually added at TUI startup.
    let src = include_str!("../event_loop.rs");
    assert!(
        src.contains("startup_project_dir_blocks"),
        "Event loop must call App::startup_project_dir_blocks() at startup"
    );
}

// ── Stage 0.6: per-App cwd ─────────────────────────────────────────────
//
// The TUI App now owns its working directory, mirroring GTK AppState.
// `App::new(model)` keeps the test-friendly default (env::current_dir()),
// `App::with_cwd(model, cwd)` is the explicit production constructor.
// `startup_project_dir_blocks()` is a method on `&self` that uses
// `self.cwd`, NOT `std::env::current_dir()`.

#[test]
fn test_app_has_cwd_field() {
    let app = App::new("m".into());
    let _: &std::path::PathBuf = &app.cwd;
}

#[test]
fn test_app_with_cwd_stores_explicit_path() {
    let cwd = std::path::PathBuf::from("/tmp/explicit-tui");
    let app = App::with_cwd("m".into(), cwd.clone());
    assert_eq!(app.cwd, cwd);
}

#[test]
fn test_app_new_defaults_cwd_to_process_cwd() {
    let app = App::new("m".into());
    let process_cwd = std::env::current_dir().unwrap();
    assert_eq!(app.cwd, process_cwd);
}

#[test]
fn test_startup_project_dir_blocks_uses_app_cwd() {
    // The method must read from self.cwd, not the process CWD.
    let cwd = std::path::PathBuf::from("/tmp/per-app-tui-marker");
    let app = App::with_cwd("m".into(), cwd);
    let blocks = app.startup_project_dir_blocks();
    match &blocks[0] {
        DisplayBlock::SystemMessage(msg) => {
            assert!(
                msg.contains("/tmp/per-app-tui-marker"),
                "SystemMessage should embed App.cwd, got: {msg}"
            );
        }
        other => panic!("expected SystemMessage, got: {other:?}"),
    }
}

#[test]
fn test_two_apps_with_different_cwd_produce_different_blocks() {
    let a = App::with_cwd("m".into(), std::path::PathBuf::from("/tmp/tui-a"));
    let b = App::with_cwd("m".into(), std::path::PathBuf::from("/tmp/tui-b"));
    let block_a = match &a.startup_project_dir_blocks()[0] {
        DisplayBlock::SystemMessage(s) => s.clone(),
        _ => panic!(),
    };
    let block_b = match &b.startup_project_dir_blocks()[0] {
        DisplayBlock::SystemMessage(s) => s.clone(),
        _ => panic!(),
    };
    assert!(block_a.contains("/tmp/tui-a"));
    assert!(block_b.contains("/tmp/tui-b"));
    assert_ne!(block_a, block_b);
}

#[test]
fn test_startup_project_dir_blocks_is_method_not_associated_function() {
    // Source-level enforcement: the function takes &self, otherwise it
    // cannot read self.cwd and would have to fall back to env::current_dir().
    let src = include_str!("../app.rs");
    assert!(
        src.contains("fn startup_project_dir_blocks(&self)"),
        "startup_project_dir_blocks must be a &self method"
    );
}

#[test]
fn test_notification_project_dir_name_takes_explicit_path() {
    // The notification helper must accept an explicit cwd, not read env.
    let name = crate::notification::project_dir_name(
        std::path::Path::new("/Users/me/projects/per-tab-name-XYZ"),
    );
    assert_eq!(name, "per-tab-name-XYZ");
}

#[test]
fn test_notification_project_dir_name_uses_path_basename() {
    let name = crate::notification::project_dir_name(std::path::Path::new("/var/lib/foo"));
    assert_eq!(name, "foo");
}

#[test]
fn test_app_does_not_call_env_current_dir_in_startup_blocks() {
    // Source-level guardrail: startup_project_dir_blocks must use self.cwd,
    // not std::env::current_dir(). Stage 0.6 of MULTIWINDOW_TABS.md.
    let src = include_str!("../app.rs");
    // Find the body of startup_project_dir_blocks and check it does not
    // contain "current_dir". Crude but sufficient.
    let needle = "fn startup_project_dir_blocks";
    let start = src.find(needle).expect("startup_project_dir_blocks defined");
    // Find the closing brace of the function — match nesting depth.
    let body_start = src[start..].find('{').unwrap() + start;
    let mut depth = 0;
    let mut end = body_start;
    for (i, c) in src[body_start..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = body_start + i + 1;
                    break;
                }
            }
            _ => {}
        }
    }
    let body = &src[body_start..end];
    assert!(
        !body.contains("env::current_dir"),
        "startup_project_dir_blocks must not call env::current_dir(); use self.cwd. Body:\n{body}"
    );
}

#[test]
fn test_notification_module_does_not_call_env_current_dir() {
    // After Stage 0.6 the notification module must accept an explicit cwd.
    let src = include_str!("../notification.rs");
    // Strip line comments before checking — the doc comment legitimately
    // mentions env::current_dir() in prose explaining that we don't use it.
    let stripped: String = src
        .lines()
        .map(|l| l.split("//").next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !stripped.contains("env::current_dir"),
        "notification.rs must not call env::current_dir() after Stage 0.6"
    );
}
