use super::*;

/// At startup, the TUI should display the project directory as the first
/// display block (a SystemMessage), followed by a `pwd` BashOutput.
/// This gives the user immediate visual feedback about which directory
/// Chlodwig is running in.

#[test]
fn test_startup_shows_project_dir_system_message() {
    // The startup display blocks are generated by `App::startup_project_dir_blocks()`.
    let blocks = App::startup_project_dir_blocks();

    // First block: SystemMessage with the project directory path
    assert!(blocks.len() >= 1, "Should have at least one startup block");
    match &blocks[0] {
        DisplayBlock::SystemMessage(msg) => {
            // Should contain the current working directory
            let cwd = std::env::current_dir()
                .map(|p| p.display().to_string())
                .unwrap_or_default();
            assert!(
                msg.contains(&cwd),
                "SystemMessage should contain CWD '{cwd}', got: {msg}"
            );
        }
        other => panic!("First startup block should be SystemMessage, got: {other:?}"),
    }
}

#[test]
fn test_startup_shows_pwd_bash_output() {
    let blocks = App::startup_project_dir_blocks();

    // Second block: BashOutput with `pwd` command
    assert!(blocks.len() >= 2, "Should have at least two startup blocks, got {}", blocks.len());
    match &blocks[1] {
        DisplayBlock::BashOutput { command, raw_output } => {
            assert_eq!(command, "pwd", "Command should be 'pwd', got: {command}");
            // The output should be a non-empty path
            let trimmed = raw_output.trim();
            assert!(!trimmed.is_empty(), "pwd output should not be empty");
            // It should be a valid path (starts with /)
            assert!(
                trimmed.starts_with('/') || trimmed.contains(':'),
                "pwd output should be an absolute path, got: {trimmed}"
            );
        }
        other => panic!("Second startup block should be BashOutput, got: {other:?}"),
    }
}

#[test]
fn test_startup_blocks_render_without_panic() {
    let mut app = App::new("test-model".into());
    let blocks = App::startup_project_dir_blocks();
    for block in blocks {
        app.display_blocks.push(block);
    }
    app.mark_dirty();
    app.rebuild_lines();

    // Should have rendered lines (at least the system message + pwd output)
    assert!(
        !app.rendered_lines.is_empty(),
        "Startup blocks should produce rendered lines"
    );
}

#[test]
fn test_startup_project_dir_contains_directory_label() {
    let blocks = App::startup_project_dir_blocks();
    match &blocks[0] {
        DisplayBlock::SystemMessage(msg) => {
            // Should have some label like "Project" or "Working directory"
            assert!(
                msg.contains("cwd"),
                "SystemMessage should contain 'cwd' label, got: {msg}"
            );
        }
        _ => panic!("Expected SystemMessage"),
    }
}

#[test]
fn test_event_loop_calls_startup_project_dir_blocks() {
    // Verify the event_loop source code calls startup_project_dir_blocks()
    // so the blocks are actually added at TUI startup.
    let src = include_str!("../event_loop.rs");
    assert!(
        src.contains("startup_project_dir_blocks"),
        "Event loop must call App::startup_project_dir_blocks() at startup"
    );
}
