    SOH();
    (hS6 = nh({ command: l8(), args: vD(l8()).optional(), env: Ru(l8(), l8()).optional() })),
      (PH7 = nh({ name: l8(), email: l8().email().optional(), url: l8().url().optional() })),
      (XH7 = nh({ type: l8(), url: l8().url() })),
      (WH7 = hS6.partial()),
      (GH7 = hS6.extend({ platform_overrides: Ru(l8(), WH7).optional() })),
      (RH7 = nh({ type: Zu(["python", "node", "binary"]), entry_point: l8(), mcp_config: GH7 })),
      (ZH7 = nh({
        claude_desktop: l8().optional(),
        platforms: vD(Zu(["darwin", "win32", "linux"])).optional(),
        runtimes: nh({ python: l8().optional(), node: l8().optional() }).optional(),
      }).passthrough()),
      (LH7 = nh({ name: l8(), description: l8().optional() })),
      (kH7 = nh({ name: l8(), description: l8().optional(), arguments: vD(l8()).optional(), text: l8() })),
      (vH7 = nh({
        type: Zu(["string", "number", "boolean", "directory", "file"]),
        title: l8(),
        description: l8(),
        required: lJ().optional(),
        default: W3H([l8(), qE(), lJ(), vD(l8())]).optional(),
        multiple: lJ().optional(),
        sensitive: lJ().optional(),
        min: qE().optional(),
        max: qE().optional(),
      })),
      (Fx4 = Ru(l8(), W3H([l8(), qE(), lJ(), vD(l8())]))),
      (HlH = nh({
        $schema: l8().optional(),
        dxt_version: l8().optional().describe("@deprecated Use manifest_version instead"),
        manifest_version: l8().optional(),
        name: l8(),
        display_name: l8().optional(),
        version: l8(),
        description: l8(),
        long_description: l8().optional(),
        author: PH7,
        repository: XH7.optional(),
        homepage: l8().url().optional(),
        documentation: l8().url().optional(),
        support: l8().url().optional(),
        icon: l8().optional(),
        screenshots: vD(l8()).optional(),
        server: RH7,
        tools: vD(LH7).optional(),
        tools_generated: lJ().optional(),
        prompts: vD(kH7).optional(),
        prompts_generated: lJ().optional(),
        keywords: vD(l8()).optional(),
        license: l8().optional(),
        privacy_policies: vD(l8()).optional(),
        compatibility: ZH7.optional(),
        user_config: Ru(l8(), vH7).optional(),
      }).refine((H) => !!(H.dxt_version || H.manifest_version), {
        message: "Either 'dxt_version' (deprecated) or 'manifest_version' must be provided",
      })),
      (Ux4 = nh({
        status: Zu(["signed", "unsigned", "self-signed"]),
        publisher: l8().optional(),
        issuer: l8().optional(),
        valid_from: l8().optional(),
        valid_to: l8().optional(),
        fingerprint: l8().optional(),
      }));
