    uA();
    NZ8();
    V5_();
    X5_();
    E$6();
    D1H();
    yZ8();
    QuH();
    Xh();
    VZ8();
    HB();
    A46();
    EZ8();
    Tj = CZ8(DMH);
    Tj.Axios = OxH;
    Tj.CanceledError = Wh;
    Tj.CancelToken = hZ8;
    Tj.isCancel = ouH;
    Tj.VERSION = X1H;
    Tj.toFormData = Vt;
    Tj.AxiosError = eq;
    Tj.Cancel = Tj.CanceledError;
    Tj.all = function (_) {
      return Promise.all(_);
    };
    Tj.spread = Y46;
    Tj.isAxiosError = D46;
    Tj.mergeConfig = GI;
    Tj.AxiosHeaders = zY;
    Tj.formToJSON = (H) => P5_(Q_.isHTMLForm(H) ? new FormData(H) : H);
    Tj.getAdapter = C5_.getAdapter;
    Tj.HttpStatusCode = SZ8;
    Tj.default = Tj;
    T6 = Tj;
