    (A1 = {
      Auto: 0,
      FlexStart: 1,
      Center: 2,
      FlexEnd: 3,
      Stretch: 4,
      Baseline: 5,
      SpaceBetween: 6,
      SpaceAround: 7,
      SpaceEvenly: 8,
    }),
      (u0_ = { Inherit: 0, LTR: 1, RTL: 2 }),
      (Ni = { Flex: 0, None: 1, Contents: 2 }),
      (KA = { Left: 0, Top: 1, Right: 2, Bottom: 3, Start: 4, End: 5, Horizontal: 6, Vertical: 7, All: 8 }),
      (Egq = {
        None: 0,
        StretchFlexBasis: 1,
        AbsolutePositionWithoutInsetsExcludesPadding: 2,
        AbsolutePercentAgainstInnerSize: 4,
        All: 2147483647,
        Classic: 2147483646,
      }),
      (P2 = { Column: 0, ColumnReverse: 1, Row: 2, RowReverse: 3 }),
      (Zg = { Column: 0, Row: 1, All: 2 }),
      (BX = { FlexStart: 0, Center: 1, FlexEnd: 2, SpaceBetween: 3, SpaceAround: 4, SpaceEvenly: 5 }),
      (d1 = { Undefined: 0, Exactly: 1, AtMost: 2 }),
      (I3H = { Visible: 0, Hidden: 1, Scroll: 2 }),
      (u3H = { Static: 0, Relative: 1, Absolute: 2 }),
      (nJ = { Undefined: 0, Point: 1, Percent: 2, Auto: 3 }),
      (hi = { NoWrap: 0, Wrap: 1, WrapReverse: 2 });
