    YE();
    Q0_();
    (Wdq = require("buffer")),
      ($Z4 = /^(?:\x1b)([a-zA-Z0-9])$/),
      (KZ4 = /^(?:\x1b+)(O|N|\[|\[\[)(?:(\d+)(?:;(\d+))?([~^$])|(?:1;)?(\d+)?([a-zA-Z]))/),
      (OZ4 = /^\x1b\[(\d+)(?:;(\d+))?u/),
      (TZ4 = /^\x1b\[27;(\d+);(\d+)~/),
      (zZ4 = /^\x1b\[\?(\d+);(\d+)\$y$/),
      (AZ4 = /^\x1b\[\?([\d;]*)c$/),
      (fZ4 = /^\x1b\[>([\d;]*)c$/),
      (wZ4 = /^\x1b\[\?(\d+)u$/),
      (YZ4 = /^\x1b\[\?(\d+);(\d+)R$/),
      (DZ4 = /^\x1b\](\d+);(.*?)(?:\x07|\x1b\\)$/s),
      (jZ4 = /^\x1bP>\|(.*?)(?:\x07|\x1b\\)$/s),
      (Gdq = /^\x1b\[<(\d+);(\d+);(\d+)([Mm])$/);
    Rdq = { mode: "NORMAL", incomplete: "", pasteBuffer: "" };
    (Ldq = {
      OP: "f1",
      OQ: "f2",
      OR: "f3",
      OS: "f4",
      Op: "0",
      Oq: "1",
      Or: "2",
      Os: "3",
      Ot: "4",
      Ou: "5",
      Ov: "6",
      Ow: "7",
      Ox: "8",
      Oy: "9",
      Oj: "*",
      Ok: "+",
      Ol: ",",
      Om: "-",
      On: ".",
      Oo: "/",
      OM: "return",
      "[11~": "f1",
      "[12~": "f2",
      "[13~": "f3",
      "[14~": "f4",
      "[[A": "f1",
      "[[B": "f2",
      "[[C": "f3",
      "[[D": "f4",
      "[[E": "f5",
      "[15~": "f5",
      "[17~": "f6",
      "[18~": "f7",
      "[19~": "f8",
      "[20~": "f9",
      "[21~": "f10",
      "[23~": "f11",
      "[24~": "f12",
      "[A": "up",
      "[B": "down",
      "[C": "right",
      "[D": "left",
      "[E": "clear",
      "[F": "end",
      "[H": "home",
      OA: "up",
      OB: "down",
      OC: "right",
      OD: "left",
      OE: "clear",
      OF: "end",
      OH: "home",
      "[1~": "home",
      "[2~": "insert",
      "[3~": "delete",
      "[4~": "end",
      "[5~": "pageup",
      "[6~": "pagedown",
      "[[5~": "pageup",
      "[[6~": "pagedown",
      "[7~": "home",
      "[8~": "end",
      "[a": "up",
      "[b": "down",
      "[c": "right",
      "[d": "left",
      "[e": "clear",
      "[2$": "insert",
      "[3$": "delete",
      "[5$": "pageup",
      "[6$": "pagedown",
      "[7$": "home",
      "[8$": "end",
      Oa: "up",
      Ob: "down",
      Oc: "right",
      Od: "left",
      Oe: "clear",
      "[2^": "insert",
      "[3^": "delete",
      "[5^": "pageup",
      "[6^": "pagedown",
      "[7^": "home",
      "[8^": "end",
      "[Z": "tab",
    }),
      (kdq = [
        ...Object.values(Ldq).filter((H) => H.length > 1),
        "escape",
        "backspace",
        "wheelup",
        "wheeldown",
        "mouse",
      ]);
