    (aY1 = ["/Applications/", "/System/Applications/"]),
      (sY1 = [
        /Helper(?:$|\s\()/,
        /Agent(?:$|\s\()/,
        /Service(?:$|\s\()/,
        /Uninstaller(?:$|\s\()/,
        /Updater(?:$|\s\()/,
        /^\./,
      ]),
      (tY1 = new Set([
        "com.apple.Safari",
        "com.google.Chrome",
        "com.microsoft.edgemac",
        "org.mozilla.firefox",
        "company.thebrowser.Browser",
        "com.tinyspeck.slackmacgap",
        "us.zoom.xos",
        "com.microsoft.teams2",
        "com.microsoft.teams",
        "com.apple.MobileSMS",
        "com.apple.mail",
        "com.microsoft.Word",
        "com.microsoft.Excel",
        "com.microsoft.Powerpoint",
        "com.microsoft.Outlook",
        "com.apple.iWork.Pages",
        "com.apple.iWork.Numbers",
        "com.apple.iWork.Keynote",
        "com.google.GoogleDocs",
        "notion.id",
        "com.apple.Notes",
        "md.obsidian",
        "com.linear",
        "com.figma.Desktop",
        "com.microsoft.VSCode",
        "com.apple.Terminal",
        "com.googlecode.iterm2",
        "com.github.GitHubDesktop",
        "com.apple.finder",
        "com.apple.iCal",
        "com.apple.systempreferences",
      ])),
      (eY1 = /^[\p{L}\p{M}\p{N}_ .&'()+-]+$/u);
