    M9();
    Rr();
    BGH();
    o21 = new Set(["--version", "--info", "--list-runtimes", "--list-sdks"]);
    (cV7 = Object.assign(Object.create(null), {
      "get-childitem": {
        safeFlags: [
          "-Path",
          "-LiteralPath",
          "-Filter",
          "-Include",
          "-Exclude",
          "-Recurse",
          "-Depth",
          "-Name",
          "-Force",
          "-Attributes",
          "-Directory",
          "-File",
          "-Hidden",
          "-ReadOnly",
          "-System",
        ],
      },
      "get-content": {
        safeFlags: [
          "-Path",
          "-LiteralPath",
          "-TotalCount",
          "-Head",
          "-Tail",
          "-Raw",
          "-Encoding",
          "-Delimiter",
          "-ReadCount",
        ],
      },
      "get-item": { safeFlags: ["-Path", "-LiteralPath", "-Force", "-Stream"] },
      "get-itemproperty": { safeFlags: ["-Path", "-LiteralPath", "-Name"] },
      "test-path": {
        safeFlags: [
          "-Path",
          "-LiteralPath",
          "-PathType",
          "-Filter",
          "-Include",
          "-Exclude",
          "-IsValid",
          "-NewerThan",
          "-OlderThan",
        ],
      },
      "resolve-path": { safeFlags: ["-Path", "-LiteralPath", "-Relative"] },
      "get-filehash": { safeFlags: ["-Path", "-LiteralPath", "-Algorithm", "-InputStream"] },
      "get-acl": { safeFlags: ["-Path", "-LiteralPath", "-Audit", "-Filter", "-Include", "-Exclude"] },
      "set-location": { safeFlags: ["-Path", "-LiteralPath", "-PassThru", "-StackName"] },
      "push-location": { safeFlags: ["-Path", "-LiteralPath", "-PassThru", "-StackName"] },
      "pop-location": { safeFlags: ["-PassThru", "-StackName"] },
      "select-string": {
        safeFlags: [
          "-Path",
          "-LiteralPath",
          "-Pattern",
          "-InputObject",
          "-SimpleMatch",
          "-CaseSensitive",
          "-Quiet",
          "-List",
          "-NotMatch",
          "-AllMatches",
          "-Encoding",
          "-Context",
          "-Raw",
          "-NoEmphasis",
        ],
      },
      "convertto-json": { safeFlags: ["-InputObject", "-Depth", "-Compress", "-EnumsAsStrings", "-AsArray"] },
      "convertfrom-json": { safeFlags: ["-InputObject", "-Depth", "-AsHashtable", "-NoEnumerate"] },
      "convertto-csv": { safeFlags: ["-InputObject", "-Delimiter", "-NoTypeInformation", "-NoHeader", "-UseQuotes"] },
      "convertfrom-csv": { safeFlags: ["-InputObject", "-Delimiter", "-Header", "-UseCulture"] },
      "convertto-xml": { safeFlags: ["-InputObject", "-Depth", "-As", "-NoTypeInformation"] },
      "convertto-html": {
        safeFlags: ["-InputObject", "-Property", "-Head", "-Title", "-Body", "-Pre", "-Post", "-As", "-Fragment"],
      },
      "format-hex": { safeFlags: ["-Path", "-LiteralPath", "-InputObject", "-Encoding", "-Count", "-Offset"] },
      "get-member": { safeFlags: ["-InputObject", "-MemberType", "-Name", "-Static", "-View", "-Force"] },
      "get-unique": { safeFlags: ["-InputObject", "-AsString", "-CaseInsensitive", "-OnType"] },
      "compare-object": {
        safeFlags: [
          "-ReferenceObject",
          "-DifferenceObject",
          "-Property",
          "-SyncWindow",
          "-CaseSensitive",
          "-Culture",
          "-ExcludeDifferent",
          "-IncludeEqual",
          "-PassThru",
        ],
      },
      "join-string": {
        safeFlags: [
          "-InputObject",
          "-Property",
          "-Separator",
          "-OutputPrefix",
          "-OutputSuffix",
          "-SingleQuote",
          "-DoubleQuote",
          "-FormatString",
        ],
      },
      "get-random": { safeFlags: ["-InputObject", "-Minimum", "-Maximum", "-Count", "-SetSeed", "-Shuffle"] },
      "convert-path": { safeFlags: ["-Path", "-LiteralPath"] },
      "join-path": { safeFlags: ["-Path", "-ChildPath", "-AdditionalChildPath"] },
      "split-path": {
        safeFlags: [
          "-Path",
          "-LiteralPath",
          "-Qualifier",
          "-NoQualifier",
          "-Parent",
          "-Leaf",
          "-LeafBase",
          "-Extension",
          "-IsAbsolute",
        ],
      },
      "get-hotfix": { safeFlags: ["-Id", "-Description"] },
      "get-itempropertyvalue": { safeFlags: ["-Path", "-LiteralPath", "-Name"] },
      "get-psprovider": { safeFlags: ["-PSProvider"] },
      "get-process": { safeFlags: ["-Name", "-Id", "-Module", "-FileVersionInfo", "-IncludeUserName"] },
      "get-service": {
        safeFlags: ["-Name", "-DisplayName", "-DependentServices", "-RequiredServices", "-Include", "-Exclude"],
      },
      "get-computerinfo": { allowAllFlags: !0 },
      "get-host": { allowAllFlags: !0 },
      "get-date": { safeFlags: ["-Date", "-Format", "-UFormat", "-DisplayHint", "-AsUTC"] },
      "get-location": { safeFlags: ["-PSProvider", "-PSDrive", "-Stack", "-StackName"] },
      "get-psdrive": { safeFlags: ["-Name", "-PSProvider", "-Scope"] },
      "get-module": { safeFlags: ["-Name", "-ListAvailable", "-All", "-FullyQualifiedName", "-PSEdition"] },
      "get-alias": { safeFlags: ["-Name", "-Definition", "-Scope", "-Exclude"] },
      "get-history": { safeFlags: ["-Id", "-Count"] },
      "get-culture": { allowAllFlags: !0 },
      "get-uiculture": { allowAllFlags: !0 },
      "get-timezone": { safeFlags: ["-Name", "-Id", "-ListAvailable"] },
      "get-uptime": { allowAllFlags: !0 },
      "write-output": { safeFlags: ["-InputObject", "-NoEnumerate"], additionalCommandIsDangerousCallback: tM },
      "start-sleep": {
        safeFlags: ["-Seconds", "-Milliseconds", "-Duration"],
        additionalCommandIsDangerousCallback: tM,
      },
      "format-table": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "format-list": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "format-wide": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "format-custom": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "measure-object": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "select-object": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "sort-object": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "group-object": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "where-object": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "out-string": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "out-host": { allowAllFlags: !0, additionalCommandIsDangerousCallback: tM },
      "get-netadapter": { safeFlags: ["-Name", "-InterfaceDescription", "-InterfaceIndex", "-Physical"] },
      "get-netipaddress": { safeFlags: ["-InterfaceIndex", "-InterfaceAlias", "-AddressFamily", "-Type"] },
      "get-netipconfiguration": { safeFlags: ["-InterfaceIndex", "-InterfaceAlias", "-Detailed", "-All"] },
      "get-netroute": { safeFlags: ["-InterfaceIndex", "-InterfaceAlias", "-AddressFamily", "-DestinationPrefix"] },
      "get-dnsclientcache": { safeFlags: ["-Entry", "-Name", "-Type", "-Status", "-Section", "-Data"] },
      "get-dnsclient": { safeFlags: ["-InterfaceIndex", "-InterfaceAlias"] },
      "get-eventlog": {
        safeFlags: [
          "-LogName",
          "-Newest",
          "-After",
          "-Before",
          "-EntryType",
          "-Index",
          "-InstanceId",
          "-Message",
          "-Source",
          "-UserName",
          "-AsBaseObject",
          "-List",
        ],
      },
      "get-winevent": {
        safeFlags: [
          "-LogName",
          "-ListLog",
          "-ListProvider",
          "-ProviderName",
          "-Path",
          "-MaxEvents",
          "-FilterXPath",
          "-Force",
          "-Oldest",
        ],
      },
      "get-cimclass": { safeFlags: ["-ClassName", "-Namespace", "-MethodName", "-PropertyName", "-QualifierName"] },
      git: {},
      gh: {},
      docker: {},
      ipconfig: {
        safeFlags: ["/all", "/displaydns", "/allcompartments"],
        additionalCommandIsDangerousCallback: (H, _) => {
          return (_?.args ?? []).some((q) => !q.startsWith("/") && !q.startsWith("-"));
        },
      },
      netstat: { safeFlags: ["-a", "-b", "-e", "-f", "-n", "-o", "-p", "-q", "-r", "-s", "-t", "-x", "-y"] },
      systeminfo: { safeFlags: ["/FO", "/NH"] },
      tasklist: { safeFlags: ["/M", "/SVC", "/V", "/FI", "/FO", "/NH"] },
      "where.exe": { allowAllFlags: !0 },
      hostname: {
        safeFlags: ["-a", "-d", "-f", "-i", "-I", "-s", "-y", "-A"],
        additionalCommandIsDangerousCallback: (H, _) => {
          return (_?.args ?? []).some((q) => !q.startsWith("-"));
        },
      },
      whoami: { safeFlags: ["/user", "/groups", "/claims", "/priv", "/logonid", "/all", "/fo", "/nh"] },
      ver: { allowAllFlags: !0 },
      arp: { safeFlags: ["-a", "-g", "-v", "-N"] },
      route: {
        safeFlags: ["print", "PRINT", "-4", "-6"],
        additionalCommandIsDangerousCallback: (H, _) => {
          if (!_) return !0;
          return _.args.find(($) => !$.startsWith("-"))?.toLowerCase() !== "print";
        },
      },
      getmac: { safeFlags: ["/FO", "/NH", "/V"] },
      file: {
        safeFlags: [
          "-b",
          "--brief",
          "-i",
          "--mime",
          "-L",
          "--dereference",
          "--mime-type",
          "--mime-encoding",
          "-z",
          "--uncompress",
          "-p",
          "--preserve-date",
          "-k",
          "--keep-going",
          "-r",
          "--raw",
          "-v",
          "--version",
          "-0",
          "--print0",
          "-s",
          "--special-files",
          "-l",
          "-F",
          "--separator",
          "-e",
          "-P",
          "-N",
          "--no-pad",
          "-E",
          "--extension",
        ],
      },
      tree: { safeFlags: ["/F", "/A", "/Q", "/L"] },
      findstr: {
        safeFlags: ["/B", "/E", "/L", "/R", "/S", "/I", "/X", "/V", "/N", "/M", "/O", "/P", "/C", "/G", "/D", "/A"],
      },
      dotnet: {},
    })),
      (a21 = new Set(["out-null"])),
      (s21 = new Set([
        "format-table",
        "format-list",
        "format-wide",
        "format-custom",
        "measure-object",
        "select-object",
        "sort-object",
        "group-object",
        "where-object",
        "out-string",
        "out-host",
      ])),
      (t21 = new Set(["where.exe"])),
      (e21 = /\.(exe|cmd|bat|com)$/);
    (qj1 = new Set(["-c", "-C", "--exec-path", "--config-env", "--git-dir", "--work-tree", "--attr-source"])),
      ($j1 = new Set([
        "-c",
        "-C",
        "--exec-path",
        "--config-env",
        "--git-dir",
        "--work-tree",
        "--namespace",
        "--super-prefix",
        "--shallow-file",
      ])),
      (Kj1 = ["-c", "-C"]);
