    (IK = {
      All: "all",
      Horizontal: "horizontal",
      Vertical: "vertical",
      Left: "left",
      Right: "right",
      Top: "top",
      Bottom: "bottom",
      Start: "start",
      End: "end",
    }),
      (a0_ = { All: "all", Column: "column", Row: "row" }),
      (eh = { Flex: "flex", None: "none" }),
      (rFH = { Row: "row", RowReverse: "row-reverse", Column: "column", ColumnReverse: "column-reverse" }),
      (ui = { Auto: "auto", Stretch: "stretch", FlexStart: "flex-start", Center: "center", FlexEnd: "flex-end" }),
      (B3H = {
        FlexStart: "flex-start",
        Center: "center",
        FlexEnd: "flex-end",
        SpaceBetween: "space-between",
        SpaceAround: "space-around",
        SpaceEvenly: "space-evenly",
      }),
      (s0_ = { NoWrap: "nowrap", Wrap: "wrap", WrapReverse: "wrap-reverse" }),
      (Uk6 = { Relative: "relative", Absolute: "absolute" }),
      (t0_ = { Visible: "visible", Hidden: "hidden", Scroll: "scroll" }),
      (E0H = { Undefined: "undefined", Exactly: "exactly", AtMost: "at-most" });
