    SOH();
    (Q$7 = ih({ command: l8(), args: vD(l8()).optional(), env: Ru(l8(), l8()).optional() })),
      (eU4 = ih({ name: l8(), email: l8().email().optional(), url: l8().url().optional() })),
      (HQ4 = ih({ type: l8(), url: l8().url() })),
      (_Q4 = Q$7.partial()),
      (qQ4 = Q$7.extend({ platform_overrides: Ru(l8(), _Q4).optional() })),
      ($Q4 = ih({ type: Zu(["python", "node", "binary"]), entry_point: l8(), mcp_config: qQ4 })),
      (KQ4 = ih({
        claude_desktop: l8().optional(),
        platforms: vD(Zu(["darwin", "win32", "linux"])).optional(),
        runtimes: ih({ python: l8().optional(), node: l8().optional() }).optional(),
      }).passthrough()),
      (OQ4 = ih({ name: l8(), description: l8().optional() })),
      (TQ4 = ih({ name: l8(), description: l8().optional(), arguments: vD(l8()).optional(), text: l8() })),
      (zQ4 = ih({
        type: Zu(["string", "number", "boolean", "directory", "file"]),
        title: l8(),
        description: l8(),
        required: lJ().optional(),
        default: W3H([l8(), qE(), lJ(), vD(l8())]).optional(),
        multiple: lJ().optional(),
        sensitive: lJ().optional(),
        min: qE().optional(),
        max: qE().optional(),
      })),
      (Ni3 = Ru(l8(), W3H([l8(), qE(), lJ(), vD(l8())]))),
      (l$7 = ih({
        $schema: l8().optional(),
        dxt_version: l8().optional().describe("@deprecated Use manifest_version instead"),
        manifest_version: l8().optional(),
        name: l8(),
        display_name: l8().optional(),
        version: l8(),
        description: l8(),
        long_description: l8().optional(),
        author: eU4,
        repository: HQ4.optional(),
        homepage: l8().url().optional(),
        documentation: l8().url().optional(),
        support: l8().url().optional(),
        icon: l8().optional(),
        screenshots: vD(l8()).optional(),
        server: $Q4,
        tools: vD(OQ4).optional(),
        tools_generated: lJ().optional(),
        prompts: vD(TQ4).optional(),
        prompts_generated: lJ().optional(),
        keywords: vD(l8()).optional(),
        license: l8().optional(),
        compatibility: KQ4.optional(),
        user_config: Ru(l8(), zQ4).optional(),
      }).refine((H) => !!(H.dxt_version || H.manifest_version), {
        message: "Either 'dxt_version' (deprecated) or 'manifest_version' must be provided",
      })),
      (hi3 = ih({
        status: Zu(["signed", "unsigned", "self-signed"]),
        publisher: l8().optional(),
        issuer: l8().optional(),
        valid_from: l8().optional(),
        valid_to: l8().optional(),
        fingerprint: l8().optional(),
      }));
