    (Jd1 = new Set([
      "platform.claude.com",
      "code.claude.com",
      "modelcontextprotocol.io",
      "github.com/anthropics",
      "agentskills.io",
      "docs.python.org",
      "en.cppreference.com",
      "docs.oracle.com",
      "learn.microsoft.com",
      "developer.mozilla.org",
      "go.dev",
      "pkg.go.dev",
      "www.php.net",
      "docs.swift.org",
      "kotlinlang.org",
      "ruby-doc.org",
      "doc.rust-lang.org",
      "www.typescriptlang.org",
      "react.dev",
      "angular.io",
      "vuejs.org",
      "nextjs.org",
      "expressjs.com",
      "nodejs.org",
      "bun.sh",
      "jquery.com",
      "getbootstrap.com",
      "tailwindcss.com",
      "d3js.org",
      "threejs.org",
      "redux.js.org",
      "webpack.js.org",
      "jestjs.io",
      "reactrouter.com",
      "docs.djangoproject.com",
      "flask.palletsprojects.com",
      "fastapi.tiangolo.com",
      "pandas.pydata.org",
      "numpy.org",
      "www.tensorflow.org",
      "pytorch.org",
      "scikit-learn.org",
      "matplotlib.org",
      "requests.readthedocs.io",
      "jupyter.org",
      "laravel.com",
      "symfony.com",
      "wordpress.org",
      "docs.spring.io",
      "hibernate.org",
      "tomcat.apache.org",
      "gradle.org",
      "maven.apache.org",
      "asp.net",
      "dotnet.microsoft.com",
      "nuget.org",
      "blazor.net",
      "reactnative.dev",
      "docs.flutter.dev",
      "developer.apple.com",
      "developer.android.com",
      "keras.io",
      "spark.apache.org",
      "huggingface.co",
      "www.kaggle.com",
      "www.mongodb.com",
      "redis.io",
      "www.postgresql.org",
      "dev.mysql.com",
      "www.sqlite.org",
      "graphql.org",
      "prisma.io",
      "docs.aws.amazon.com",
      "cloud.google.com",
      "learn.microsoft.com",
      "kubernetes.io",
      "www.docker.com",
      "www.terraform.io",
      "www.ansible.com",
      "vercel.com/docs",
      "docs.netlify.com",
      "devcenter.heroku.com",
      "cypress.io",
      "selenium.dev",
      "docs.unity.com",
      "docs.unrealengine.com",
      "git-scm.com",
      "nginx.org",
      "httpd.apache.org",
    ])),
      ({ HOSTNAME_ONLY: Pd1, PATH_PREFIXES: Xd1 } = (() => {
        let H = new Set(),
          _ = new Map();
        for (let q of Jd1) {
          let $ = q.indexOf("/");
          if ($ === -1) H.add(q);
          else {
            let K = q.slice(0, $),
              O = q.slice($),
              T = _.get(K);
            if (T) T.push(O);
            else _.set(K, [O]);
          }
        }
        return { HOSTNAME_ONLY: H, PATH_PREFIXES: _ };
      })());
