    x8();
    (YW = S76()
      .superRefine((H, _) => {
        if (!URL.canParse(H)) return _.addIssue({ code: _96.custom, message: "URL must be parseable", fatal: !0 }), NIH;
      })
      .refine(
        (H) => {
          let _ = new URL(H);
          return _.protocol !== "javascript:" && _.protocol !== "data:" && _.protocol !== "vbscript:";
        },
        { message: "URL cannot use javascript:, data:, or vbscript: scheme" },
      )),
      (yR7 = Kj({
        resource: c_().url(),
        authorization_servers: gq(YW).optional(),
        jwks_uri: c_().url().optional(),
        scopes_supported: gq(c_()).optional(),
        bearer_methods_supported: gq(c_()).optional(),
        resource_signing_alg_values_supported: gq(c_()).optional(),
        resource_name: c_().optional(),
        resource_documentation: c_().optional(),
        resource_policy_uri: c_().url().optional(),
        resource_tos_uri: c_().url().optional(),
        tls_client_certificate_bound_access_tokens: uT().optional(),
        authorization_details_types_supported: gq(c_()).optional(),
        dpop_signing_alg_values_supported: gq(c_()).optional(),
        dpop_bound_access_tokens_required: uT().optional(),
      })),
      (krH = Kj({
        issuer: c_(),
        authorization_endpoint: YW,
        token_endpoint: YW,
        registration_endpoint: YW.optional(),
        scopes_supported: gq(c_()).optional(),
        response_types_supported: gq(c_()),
        response_modes_supported: gq(c_()).optional(),
        grant_types_supported: gq(c_()).optional(),
        token_endpoint_auth_methods_supported: gq(c_()).optional(),
        token_endpoint_auth_signing_alg_values_supported: gq(c_()).optional(),
        service_documentation: YW.optional(),
        revocation_endpoint: YW.optional(),
        revocation_endpoint_auth_methods_supported: gq(c_()).optional(),
        revocation_endpoint_auth_signing_alg_values_supported: gq(c_()).optional(),
        introspection_endpoint: c_().optional(),
        introspection_endpoint_auth_methods_supported: gq(c_()).optional(),
        introspection_endpoint_auth_signing_alg_values_supported: gq(c_()).optional(),
        code_challenge_methods_supported: gq(c_()).optional(),
        client_id_metadata_document_supported: uT().optional(),
      })),
      (UT1 = Kj({
        issuer: c_(),
        authorization_endpoint: YW,
        token_endpoint: YW,
        userinfo_endpoint: YW.optional(),
        jwks_uri: YW,
        registration_endpoint: YW.optional(),
        scopes_supported: gq(c_()).optional(),
        response_types_supported: gq(c_()),
        response_modes_supported: gq(c_()).optional(),
        grant_types_supported: gq(c_()).optional(),
        acr_values_supported: gq(c_()).optional(),
        subject_types_supported: gq(c_()),
        id_token_signing_alg_values_supported: gq(c_()),
        id_token_encryption_alg_values_supported: gq(c_()).optional(),
        id_token_encryption_enc_values_supported: gq(c_()).optional(),
        userinfo_signing_alg_values_supported: gq(c_()).optional(),
        userinfo_encryption_alg_values_supported: gq(c_()).optional(),
        userinfo_encryption_enc_values_supported: gq(c_()).optional(),
        request_object_signing_alg_values_supported: gq(c_()).optional(),
        request_object_encryption_alg_values_supported: gq(c_()).optional(),
        request_object_encryption_enc_values_supported: gq(c_()).optional(),
        token_endpoint_auth_methods_supported: gq(c_()).optional(),
        token_endpoint_auth_signing_alg_values_supported: gq(c_()).optional(),
        display_values_supported: gq(c_()).optional(),
        claim_types_supported: gq(c_()).optional(),
        claims_supported: gq(c_()).optional(),
        service_documentation: c_().optional(),
        claims_locales_supported: gq(c_()).optional(),
        ui_locales_supported: gq(c_()).optional(),
        claims_parameter_supported: uT().optional(),
        request_parameter_supported: uT().optional(),
        request_uri_parameter_supported: uT().optional(),
        require_request_uri_registration: uT().optional(),
        op_policy_uri: YW.optional(),
        op_tos_uri: YW.optional(),
        client_id_metadata_document_supported: uT().optional(),
      })),
      (uV_ = tq({ ...UT1.shape, ...krH.pick({ code_challenge_methods_supported: !0 }).shape })),
      (xV_ = tq({
        access_token: c_(),
        id_token: c_().optional(),
        token_type: c_(),
        expires_in: juH.number().optional(),
        scope: c_().optional(),
        refresh_token: c_().optional(),
      }).strip()),
      (vrH = tq({ error: c_(), error_description: c_().optional(), error_uri: c_().optional() })),
      (hR7 = YW.optional().or(
        A9("").transform(() => {
          return;
        }),
      )),
      (QT1 = tq({
        redirect_uris: gq(YW),
        token_endpoint_auth_method: c_().optional(),
        grant_types: gq(c_()).optional(),
        response_types: gq(c_()).optional(),
        client_name: c_().optional(),
        client_uri: YW.optional(),
        logo_uri: hR7,
        scope: c_().optional(),
        contacts: gq(c_()).optional(),
        tos_uri: hR7,
        policy_uri: c_().optional(),
        jwks_uri: YW.optional(),
        jwks: i76().optional(),
        software_id: c_().optional(),
        software_version: c_().optional(),
        software_statement: c_().optional(),
      }).strip()),
      (lT1 = tq({
        client_id: c_(),
        client_secret: c_().optional(),
        client_id_issued_at: Y3().optional(),
        client_secret_expires_at: Y3().optional(),
      }).strip()),
      (VR7 = QT1.merge(lT1)),
      (rfO = tq({ error: c_(), error_description: c_().optional() }).strip()),
      (ofO = tq({ token: c_(), token_type_hint: c_().optional() }).strip());
