    wT(); /*! @azure/msal-node v3.8.1 2025-10-29 */
    (uM6 = `https://login.microsoftonline.com/${eH4}/`),
      (Jk = {
        AUTHORIZATION_HEADER_NAME: "Authorization",
        METADATA_HEADER_NAME: "Metadata",
        APP_SERVICE_SECRET_HEADER_NAME: "X-IDENTITY-HEADER",
        ML_AND_SF_SECRET_HEADER_NAME: "secret",
      }),
      (Xj = {
        API_VERSION: "api-version",
        RESOURCE: "resource",
        SHA256_TOKEN_TO_REFRESH: "token_sha256_to_refresh",
        XMS_CC: "xms_cc",
      }),
      (e$ = {
        AZURE_POD_IDENTITY_AUTHORITY_HOST: "AZURE_POD_IDENTITY_AUTHORITY_HOST",
        DEFAULT_IDENTITY_CLIENT_ID: "DEFAULT_IDENTITY_CLIENT_ID",
        IDENTITY_ENDPOINT: "IDENTITY_ENDPOINT",
        IDENTITY_HEADER: "IDENTITY_HEADER",
        IDENTITY_SERVER_THUMBPRINT: "IDENTITY_SERVER_THUMBPRINT",
        IMDS_ENDPOINT: "IMDS_ENDPOINT",
        MSI_ENDPOINT: "MSI_ENDPOINT",
        MSI_SECRET: "MSI_SECRET",
      }),
      (R4 = {
        APP_SERVICE: "AppService",
        AZURE_ARC: "AzureArc",
        CLOUD_SHELL: "CloudShell",
        DEFAULT_TO_IMDS: "DefaultToImds",
        IMDS: "Imds",
        MACHINE_LEARNING: "MachineLearning",
        SERVICE_FABRIC: "ServiceFabric",
      }),
      (WY = {
        SYSTEM_ASSIGNED: "system-assigned",
        USER_ASSIGNED_CLIENT_ID: "user-assigned-client-id",
        USER_ASSIGNED_RESOURCE_ID: "user-assigned-resource-id",
        USER_ASSIGNED_OBJECT_ID: "user-assigned-object-id",
      }),
      (kf = { GET: "get", POST: "post" }),
      (wj_ = {
        SUCCESS_RANGE_START: Q4.SUCCESS_RANGE_START,
        SUCCESS_RANGE_END: Q4.SUCCESS_RANGE_END,
        SERVER_ERROR: Q4.SERVER_ERROR,
      }),
      (Zjq = { SHA256: "sha256" }),
      (Yj_ = { CV_CHARSET: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~" }),
      (xM6 = { KEY_SEPARATOR: "-" }),
      (wZ = {
        MSAL_SKU: "msal.js.node",
        JWT_BEARER_ASSERTION_TYPE: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
        AUTHORIZATION_PENDING: "authorization_pending",
        HTTP_PROTOCOL: "http://",
        LOCALHOST: "localhost",
      }),
      (Cl = {
        acquireTokenSilent: 62,
        acquireTokenByUsernamePassword: 371,
        acquireTokenByDeviceCode: 671,
        acquireTokenByClientCredential: 771,
        acquireTokenByCode: 871,
        acquireTokenByRefreshToken: 872,
      }),
      (dS = {
        RSA_256: "RS256",
        PSS_256: "PS256",
        X5T_256: "x5t#S256",
        X5T: "x5t",
        X5C: "x5c",
        AUDIENCE: "aud",
        EXPIRATION_TIME: "exp",
        ISSUER: "iss",
        SUBJECT: "sub",
        NOT_BEFORE: "nbf",
        JWT_ID: "jti",
      }),
      (Dj_ = { INTERVAL_MS: 100, TIMEOUT_MS: 5000 });
