    zx6();
    dTH();
    (E41 = new Set(["program", "list", "pipeline", "redirected_statement"])),
      (C41 = new Set([
        "&&",
        "||",
        "|",
        ";",
        "&",
        "|&",
        `
`,
      ]));
    (b41 = /[ \t\n*?[]/),
      (I41 = new Set([
        "HOME",
        "PWD",
        "OLDPWD",
        "USER",
        "LOGNAME",
        "SHELL",
        "PATH",
        "HOSTNAME",
        "UID",
        "EUID",
        "PPID",
        "RANDOM",
        "SECONDS",
        "LINENO",
        "TMPDIR",
        "BASH_VERSION",
        "BASHPID",
        "SHLVL",
        "HISTFILE",
        "IFS",
      ])),
      (u41 = new Set(["?", "$", "!", "#", "0", "-"])),
      (xJ7 = new Set([
        "command_substitution",
        "process_substitution",
        "expansion",
        "simple_expansion",
        "brace_expression",
        "subshell",
        "compound_statement",
        "for_statement",
        "while_statement",
        "until_statement",
        "if_statement",
        "case_statement",
        "function_definition",
        "test_command",
        "ansi_c_string",
        "translated_string",
        "herestring_redirect",
        "heredoc_redirect",
      ])),
      (x41 = [...xJ7]);
    (CJ7 = {
      ">": ">",
      ">>": ">>",
      "<": "<",
      ">&": ">&",
      "<&": "<&",
      ">|": ">|",
      "&>": "&>",
      "&>>": "&>>",
      "<<<": "<<<",
    }),
      (Yx6 = /\{[^{}\s]*(,|\.\.)[^{}\s]*\}/),
      (m41 = /[\x00-\x08\x0B-\x1F\x7F]/),
      (p41 = /[\u00A0\u1680\u2000-\u200B\u2028\u2029\u202F\u205F\u3000\uFEFF]/),
      (B41 = /\\[ \t]|[^ \t\n\\]\\\n/),
      (g41 = /~\[/),
      (d41 = /(?:^|[\s;&|])=[a-zA-Z_]/),
      (c41 = /\{[^}]*['"]/);
    bJ7 = String.fromCharCode(36);
    n41 =
      /^(?:[0-9]+|0[xX][0-9a-fA-F]+|[0-9]+#[0-9a-zA-Z]+|[-+*/%^&|~!<>=?:(),]+|<<|>>|\*\*|&&|\|\||[<>=!]=|\$\(\(|\)\))$/;
    (o41 = new Set([
      "zmodload",
      "emulate",
      "sysopen",
      "sysread",
      "syswrite",
      "sysseek",
      "zpty",
      "ztcp",
      "zsocket",
      "zf_rm",
      "zf_mv",
      "zf_ln",
      "zf_chmod",
      "zf_chown",
      "zf_mkdir",
      "zf_rmdir",
      "zf_chgrp",
    ])),
      (a41 = new Set([
        "eval",
        "source",
        ".",
        "exec",
        "command",
        "builtin",
        "fc",
        "coproc",
        "noglob",
        "nocorrect",
        "trap",
        "enable",
        "mapfile",
        "readarray",
        "hash",
        "bind",
        "complete",
        "compgen",
        "alias",
        "let",
      ])),
      (s41 = {
        test: new Set(["-v", "-R"]),
        "[": new Set(["-v", "-R"]),
        "[[": new Set(["-v", "-R"]),
        printf: new Set(["-v"]),
        read: new Set(["-a"]),
        unset: new Set(["-v"]),
        wait: new Set(["-p"]),
      }),
      (t41 = new Set(["-eq", "-ne", "-lt", "-le", "-gt", "-ge"])),
      (e41 = new Set(["read", "unset"])),
      (uJ7 = new Set(["-p", "-d", "-n", "-N", "-t", "-u", "-i"])),
      (jx6 = /\/proc\/.*\/environ/),
      (Th_ = /\n[ \t]*#/);
