    (nY6 = "X-Amz-Date".toLowerCase()),
      (Wzq = ["authorization", nY6, "date"]),
      (Gzq = "X-Amz-Signature".toLowerCase()),
      (Rzq = "X-Amz-Security-Token".toLowerCase()),
      (Zzq = {
        authorization: !0,
        "cache-control": !0,
        connection: !0,
        expect: !0,
        from: !0,
        "keep-alive": !0,
        "max-forwards": !0,
        pragma: !0,
        referer: !0,
        te: !0,
        trailer: !0,
        "transfer-encoding": !0,
        upgrade: !0,
        "user-agent": !0,
        "x-amzn-trace-id": !0,
      }),
      (Lzq = /^proxy-/),
      (kzq = /^sec-/);
