    I8();
    n8();
    h5();
    q5();
    uY();
    gQH();
    M9();
    Rr();
    dkH();
    (iV7 = require("os")),
      (Oc = require("path")),
      (nV7 = /[*?[\]]/),
      (Dj1 = ["-verbose", "-debug"]),
      (jj1 = [
        "-erroraction",
        "-warningaction",
        "-informationaction",
        "-progressaction",
        "-errorvariable",
        "-warningvariable",
        "-informationvariable",
        "-outvariable",
        "-outbuffer",
        "-pipelinevariable",
      ]),
      (Qd6 = {
        "set-content": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [
            "-passthru",
            "-force",
            "-whatif",
            "-confirm",
            "-usetransaction",
            "-nonewline",
            "-asbytestream",
          ],
          knownValueParams: ["-value", "-filter", "-include", "-exclude", "-credential", "-encoding", "-stream"],
        },
        "add-content": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [
            "-passthru",
            "-force",
            "-whatif",
            "-confirm",
            "-usetransaction",
            "-nonewline",
            "-asbytestream",
          ],
          knownValueParams: ["-value", "-filter", "-include", "-exclude", "-credential", "-encoding", "-stream"],
        },
        "remove-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-recurse", "-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential", "-stream"],
        },
        "clear-content": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential", "-stream"],
        },
        "out-file": {
          operationType: "write",
          pathParams: ["-filepath", "-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-append", "-force", "-noclobber", "-nonewline", "-whatif", "-confirm"],
          knownValueParams: ["-inputobject", "-encoding", "-width"],
        },
        "tee-object": {
          operationType: "write",
          pathParams: ["-filepath", "-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-append"],
          knownValueParams: ["-inputobject", "-variable", "-encoding"],
        },
        "export-csv": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [
            "-append",
            "-force",
            "-noclobber",
            "-notypeinformation",
            "-includetypeinformation",
            "-useculture",
            "-noheader",
            "-whatif",
            "-confirm",
          ],
          knownValueParams: ["-inputobject", "-delimiter", "-encoding", "-quotefields", "-usequotes"],
        },
        "export-clixml": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-noclobber", "-whatif", "-confirm"],
          knownValueParams: ["-inputobject", "-depth", "-encoding"],
        },
        "new-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          leafOnlyPathParams: ["-name"],
          knownSwitches: ["-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-itemtype", "-value", "-credential", "-type"],
        },
        "copy-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp", "-destination"],
          knownSwitches: ["-container", "-force", "-passthru", "-recurse", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential", "-fromsession", "-tosession"],
        },
        "move-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp", "-destination"],
          knownSwitches: ["-force", "-passthru", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential"],
        },
        "rename-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-passthru", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-newname", "-credential", "-filter", "-include", "-exclude"],
        },
        "set-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-passthru", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-value", "-credential", "-filter", "-include", "-exclude"],
        },
        "get-content": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-usetransaction", "-wait", "-raw", "-asbytestream"],
          knownValueParams: [
            "-readcount",
            "-totalcount",
            "-tail",
            "-first",
            "-head",
            "-last",
            "-filter",
            "-include",
            "-exclude",
            "-credential",
            "-delimiter",
            "-encoding",
            "-stream",
          ],
        },
        "get-childitem": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [
            "-recurse",
            "-force",
            "-name",
            "-usetransaction",
            "-followsymlink",
            "-directory",
            "-file",
            "-hidden",
            "-readonly",
            "-system",
          ],
          knownValueParams: ["-filter", "-include", "-exclude", "-depth", "-attributes", "-credential"],
        },
        "get-item": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential", "-stream"],
        },
        "get-itemproperty": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-usetransaction"],
          knownValueParams: ["-name", "-filter", "-include", "-exclude", "-credential"],
        },
        "get-itempropertyvalue": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-usetransaction"],
          knownValueParams: ["-name", "-filter", "-include", "-exclude", "-credential"],
        },
        "get-filehash": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [],
          knownValueParams: ["-algorithm", "-inputstream"],
        },
        "get-acl": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-audit", "-allcentralaccesspolicies", "-usetransaction"],
          knownValueParams: ["-inputobject", "-filter", "-include", "-exclude"],
        },
        "format-hex": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-raw"],
          knownValueParams: ["-inputobject", "-encoding", "-count", "-offset"],
        },
        "test-path": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-isvalid", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-pathtype", "-credential", "-olderthan", "-newerthan"],
        },
        "resolve-path": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-relative", "-usetransaction", "-force"],
          knownValueParams: ["-credential", "-relativebasepath"],
        },
        "convert-path": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-usetransaction"],
          knownValueParams: [],
        },
        "select-string": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [
            "-simplematch",
            "-casesensitive",
            "-quiet",
            "-list",
            "-notmatch",
            "-allmatches",
            "-noemphasis",
            "-raw",
          ],
          knownValueParams: ["-inputobject", "-pattern", "-include", "-exclude", "-encoding", "-context", "-culture"],
        },
        "set-location": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-passthru", "-usetransaction"],
          knownValueParams: ["-stackname"],
        },
        "push-location": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-passthru", "-usetransaction"],
          knownValueParams: ["-stackname"],
        },
        "pop-location": {
          operationType: "read",
          pathParams: [],
          knownSwitches: ["-passthru", "-usetransaction"],
          knownValueParams: ["-stackname"],
        },
        "select-xml": {
          operationType: "read",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: [],
          knownValueParams: ["-xml", "-content", "-xpath", "-namespace"],
        },
        "get-winevent": {
          operationType: "read",
          pathParams: ["-path"],
          knownSwitches: ["-force", "-oldest"],
          knownValueParams: [
            "-listlog",
            "-logname",
            "-listprovider",
            "-providername",
            "-maxevents",
            "-computername",
            "-credential",
            "-filterxpath",
            "-filterxml",
            "-filterhashtable",
          ],
        },
        "invoke-webrequest": {
          operationType: "write",
          pathParams: ["-outfile", "-infile"],
          positionalSkip: 1,
          optionalWrite: !0,
          knownSwitches: [
            "-allowinsecureredirect",
            "-allowunencryptedauthentication",
            "-disablekeepalive",
            "-nobodyprogress",
            "-passthru",
            "-preservefileauthorizationmetadata",
            "-resume",
            "-skipcertificatecheck",
            "-skipheadervalidation",
            "-skiphttperrorcheck",
            "-usebasicparsing",
            "-usedefaultcredentials",
          ],
          knownValueParams: [
            "-uri",
            "-method",
            "-body",
            "-contenttype",
            "-headers",
            "-maximumredirection",
            "-maximumretrycount",
            "-proxy",
            "-proxycredential",
            "-retryintervalsec",
            "-sessionvariable",
            "-timeoutsec",
            "-token",
            "-transferencoding",
            "-useragent",
            "-websession",
            "-credential",
            "-authentication",
            "-certificate",
            "-certificatethumbprint",
            "-form",
            "-httpversion",
          ],
        },
        "invoke-restmethod": {
          operationType: "write",
          pathParams: ["-outfile", "-infile"],
          positionalSkip: 1,
          optionalWrite: !0,
          knownSwitches: [
            "-allowinsecureredirect",
            "-allowunencryptedauthentication",
            "-disablekeepalive",
            "-followrellink",
            "-nobodyprogress",
            "-passthru",
            "-preservefileauthorizationmetadata",
            "-resume",
            "-skipcertificatecheck",
            "-skipheadervalidation",
            "-skiphttperrorcheck",
            "-usebasicparsing",
            "-usedefaultcredentials",
          ],
          knownValueParams: [
            "-uri",
            "-method",
            "-body",
            "-contenttype",
            "-headers",
            "-maximumfollowrellink",
            "-maximumredirection",
            "-maximumretrycount",
            "-proxy",
            "-proxycredential",
            "-responseheaderstvariable",
            "-retryintervalsec",
            "-sessionvariable",
            "-statuscodevariable",
            "-timeoutsec",
            "-token",
            "-transferencoding",
            "-useragent",
            "-websession",
            "-credential",
            "-authentication",
            "-certificate",
            "-certificatethumbprint",
            "-form",
            "-httpversion",
          ],
        },
        "expand-archive": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp", "-destinationpath"],
          knownSwitches: ["-force", "-passthru", "-whatif", "-confirm"],
          knownValueParams: [],
        },
        "compress-archive": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp", "-destinationpath"],
          knownSwitches: ["-force", "-update", "-passthru", "-whatif", "-confirm"],
          knownValueParams: ["-compressionlevel"],
        },
        "set-itemproperty": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-passthru", "-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: [
            "-name",
            "-value",
            "-type",
            "-filter",
            "-include",
            "-exclude",
            "-credential",
            "-inputobject",
          ],
        },
        "new-itemproperty": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: [
            "-name",
            "-value",
            "-propertytype",
            "-type",
            "-filter",
            "-include",
            "-exclude",
            "-credential",
          ],
        },
        "remove-itemproperty": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-name", "-filter", "-include", "-exclude", "-credential"],
        },
        "clear-item": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-force", "-whatif", "-confirm", "-usetransaction"],
          knownValueParams: ["-filter", "-include", "-exclude", "-credential"],
        },
        "export-alias": {
          operationType: "write",
          pathParams: ["-path", "-literalpath", "-pspath", "-lp"],
          knownSwitches: ["-append", "-force", "-noclobber", "-passthru", "-whatif", "-confirm"],
          knownValueParams: ["-name", "-description", "-scope", "-as"],
        },
      });
    Jj1 = new Set(["StringConstant", "Parameter"]);
