    m3H();
    (Vk6 = th + String.fromCharCode(xu.CSI)),
      (k0H = {
        PARAM_START: 48,
        PARAM_END: 63,
        INTERMEDIATE_START: 32,
        INTERMEDIATE_END: 47,
        FINAL_START: 64,
        FINAL_END: 126,
      });
    (Lw = {
      CUU: 65,
      CUD: 66,
      CUF: 67,
      CUB: 68,
      CNL: 69,
      CPL: 70,
      CHA: 71,
      CUP: 72,
      CHT: 73,
      VPA: 100,
      HVP: 102,
      ED: 74,
      EL: 75,
      ECH: 88,
      IL: 76,
      DL: 77,
      ICH: 64,
      DCH: 80,
      SU: 83,
      SD: 84,
      SM: 104,
      RM: 108,
      SGR: 109,
      DSR: 110,
      DECSCUSR: 113,
      DECSTBM: 114,
      SCOSC: 115,
      SCORC: 117,
      CBT: 90,
    }),
      (tgq = ["toEnd", "toStart", "all", "scrollback"]),
      (egq = ["toEnd", "toStart", "all"]),
      (Sk6 = [
        { style: "block", blinking: !0 },
        { style: "block", blinking: !0 },
        { style: "block", blinking: !1 },
        { style: "underline", blinking: !0 },
        { style: "underline", blinking: !1 },
        { style: "bar", blinking: !0 },
        { style: "bar", blinking: !1 },
      ]);
    _Z4 = g3("G");
    Ci = g3("H");
    (NV3 = g3("s")), (hV3 = g3("u")), (qZ4 = g3(2, "K")), (N0H = g3(2, "J")), (qdq = g3(3, "J"));
    (zdq = g3("r")),
      (Adq = g3("200~")),
      (fdq = g3("201~")),
      (wdq = g3("I")),
      (Ydq = g3("O")),
      (cFH = g3(">1u")),
      (bi = g3("<u")),
      (FFH = g3(">4;2m")),
      (p3H = g3(">4m"));
