    L_();
    ux6();
    Bx6();
    Cj();
    (gx6 = /\$\(.*<</),
      (i11 = [
        { pattern: /<\(/, message: "process substitution <()" },
        { pattern: />\(/, message: "process substitution >()" },
        { pattern: /=\(/, message: "Zsh process substitution =()" },
        { pattern: /(?:^|[\s;&|])=[a-zA-Z_]/, message: "Zsh equals expansion (=cmd)" },
        { pattern: /\$\(/, message: "$() command substitution" },
        { pattern: /\$\{/, message: "${} parameter substitution" },
        { pattern: /\$\[/, message: "$[] legacy arithmetic expansion" },
        { pattern: /~\[/, message: "Zsh-style parameter expansion" },
        { pattern: /\(e:/, message: "Zsh-style glob qualifiers" },
        { pattern: /\(\+/, message: "Zsh glob qualifier with command execution" },
        { pattern: /\}\s*always\s*\{/, message: "Zsh always block (try/always construct)" },
        { pattern: /<#/, message: "PowerShell comment syntax" },
      ]),
      (n11 = new Set([
        "zmodload",
        "emulate",
        "sysopen",
        "sysread",
        "syswrite",
        "sysseek",
        "zpty",
        "ztcp",
        "zsocket",
        "mapfile",
        "zf_rm",
        "zf_mv",
        "zf_ln",
        "zf_chmod",
        "zf_chown",
        "zf_mkdir",
        "zf_rmdir",
        "zf_chgrp",
      ])),
      (Q1 = {
        INCOMPLETE_COMMANDS: 1,
        JQ_SYSTEM_FUNCTION: 2,
        JQ_FILE_ARGUMENTS: 3,
        OBFUSCATED_FLAGS: 4,
        SHELL_METACHARACTERS: 5,
        DANGEROUS_VARIABLES: 6,
        NEWLINES: 7,
        DANGEROUS_PATTERNS_COMMAND_SUBSTITUTION: 8,
        DANGEROUS_PATTERNS_INPUT_REDIRECTION: 9,
        DANGEROUS_PATTERNS_OUTPUT_REDIRECTION: 10,
        IFS_INJECTION: 11,
        GIT_COMMIT_SUBSTITUTION: 12,
        PROC_ENVIRON_ACCESS: 13,
        MALFORMED_TOKEN_INJECTION: 14,
        BACKSLASH_ESCAPED_WHITESPACE: 15,
        BRACE_EXPANSION: 16,
        CONTROL_CHARACTERS: 17,
        UNICODE_WHITESPACE: 18,
        MID_WORD_HASH: 19,
        ZSH_DANGEROUS_COMMANDS: 20,
        BACKSLASH_ESCAPED_OPERATORS: 21,
        COMMENT_QUOTE_DESYNC: 22,
        QUOTED_NEWLINE: 23,
      });
    s11 = new Set([";", "|", "&", "<", ">"]);
    e11 = /[\u00A0\u1680\u2000-\u200A\u2028\u2029\u202F\u205F\u3000\uFEFF]/;
    _X7 = /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/;
