    (Nw1 = {
      meta: "meta",
      super: "meta",
      command: "meta",
      cmd: "meta",
      windows: "meta",
      win: "meta",
      ctrl: "ctrl",
      control: "ctrl",
      lctrl: "ctrl",
      lcontrol: "ctrl",
      rctrl: "ctrl",
      rcontrol: "ctrl",
      shift: "shift",
      lshift: "shift",
      rshift: "shift",
      alt: "alt",
      option: "alt",
    }),
      (Tv7 = ["ctrl", "alt", "shift", "meta"]),
      (hw1 = new Set(["meta+q", "shift+meta+q", "alt+meta+escape", "meta+tab", "meta+space", "ctrl+meta+q"])),
      (yw1 = new Set(["ctrl+alt+delete", "alt+f4", "alt+tab", "meta+l", "meta+d"]));
